const adminItems=[['dashboard','Dashboard','fa-house'],['contributions','Contributions','fa-money-bill-wave'],['members','Members','fa-users'],['transactions','Transactions','fa-arrow-right-arrow-left'],['invite','Invite','fa-link'],['profile','Profile','fa-user']];
const memberItems=[['dashboard','Dashboard','fa-house'],['contributions','Contributions','fa-money-bill-wave'],['transactions','Transactions','fa-clock-rotate-left'],['profile','Profile','fa-user']];
const role=location.pathname.includes('/admin/')?'admin':'member';
const route=location.pathname.split('/').pop().replace('.html','');
if(shell(role,role==='admin'?adminItems:memberItems,route)){
const main=$('.main');
const team=S.team;
const moneyStatus=p=>p?badge(p.st):'<span class="badge b-bad">Not submitted</span>';
const pageHead=(eyebrow,title,description,action='')=>`<header class="page-head"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div>${action}</header>`;
const statCard=(label,value,icon='fa-circle')=>`<article class="stat-card"><span class="stat-icon"><i class="fa-solid ${icon}" aria-hidden="true"></i></span><span class="stat-label">${label}</span><strong>${value}</strong></article>`;
const memberRows=(query='')=>NAMES.filter(name=>name.toLowerCase().includes(query.toLowerCase())).map(name=>{const p=S.pay.find(x=>x.m===name),paid=p&&p.st==='ok';return `<tr><td data-label="Member"><span class="table-person"><span class="avatar">${initials(name)}</span><b>${name}</b></span></td><td data-label="Username">@${name.split(' ')[0].toLowerCase()}</td><td data-label="Monthly">${fmt(team.amt)}</td><td data-label="This month">${p?badge(p.st):'<span class="badge b-bad">Unpaid</span>'}</td><td data-label="Contributed">${fmt(100000+(paid?team.amt:0))}</td></tr>`}).join('');
const contributionRows=()=>S.pay.map(p=>`<tr><td data-label="Member"><span class="table-person"><span class="avatar">${initials(p.m)}</span><b>${p.m}</b></span></td><td data-label="Amount">${fmt(p.amt)}</td><td data-label="Reference">${p.ref}</td><td data-label="Date">${p.date}</td><td data-label="Status">${badge(p.st)}</td><td data-label="Actions">${p.st==='wait'?`<button class="btn compact" data-confirm-payment="${p.id}">Confirm</button> <button class="btn compact secondary" data-reject-payment="${p.id}">Reject</button>`:'<span class="muted">No action</span>'}</td></tr>`).join('');
const latestActivity=items=>items.map(item=>`<li class="activity-row"><span class="activity-dot ${item.tone||''}"><i class="fa-solid ${item.icon}" aria-hidden="true"></i></span><span class="activity-copy"><b>${item.title}</b><small>${item.note}</small></span><strong>${item.value}</strong></li>`).join('');

function renderAdminDashboard(){
 const paid=S.pay.filter(p=>p.st==='ok').length,pending=S.pay.filter(p=>p.st==='wait').length;
 main.innerHTML=`${pageHead('ADMIN WORKSPACE',`Welcome, ${(S.user.name||'Admin').split(' ')[0]}`,'Here is your group at a glance.', '<a class="btn" href="invite.html"><i class="fa-solid fa-user-plus"></i> Invite members</a>')}
 <section class="stat-grid">${statCard('Members',NAMES.length,'fa-users')}${statCard('Monthly contribution',fmt(team.amt),'fa-coins')}${statCard('Confirmed this cycle',`${paid} / ${S.pay.length}`,'fa-circle-check')}${statCard('Awaiting review',pending,'fa-hourglass-half')}</section>
 <section class="dashboard-columns"><article class="panel balance-panel"><div class="panel-title"><div><span class="eyebrow">RECORDED AJO BALANCE</span><h2>${fmt(balance())}</h2></div><span class="round-icon"><i class="fa-solid fa-wallet"></i></span></div><p>This is your confirmed contribution total minus recorded payouts.</p><a class="text-link" href="transactions.html">Review transactions <i class="fa-solid fa-arrow-right"></i></a></article>
 <article class="panel"><div class="panel-heading"><div><span class="eyebrow">CURRENT CYCLE</span><h2>${team.cycle}</h2></div><a class="text-link" href="contributions.html">View all</a></div><div class="progress-copy"><b>${paid} of ${S.pay.length} members paid</b><span>${Math.round(paid/Math.max(S.pay.length,1)*100)}%</span></div><div class="progress-track"><span style="width:${paid/Math.max(S.pay.length,1)*100}%"></span></div><p class="muted">${fmt(confirmed())} confirmed of ${fmt(team.amt*S.pay.length)} expected</p></article></section>
 <section class="panel"><div class="panel-heading"><div><span class="eyebrow">COLLECTION TREND</span><h2>Monthly collection</h2></div><a class="text-link" href="transactions.html">View payouts</a></div><div class="chart-bars" id="collection-chart" role="img" aria-label="Monthly collection bar chart"></div></section>
 <section class="panel"><div class="panel-heading"><div><span class="eyebrow">RECENT ACTIVITY</span><h2>Latest contributions</h2></div><a class="text-link" href="contributions.html">Open contributions</a></div><div class="table-wrap"><table><thead><tr><th>Member</th><th>Amount</th><th>Reference</th><th>Date</th><th>Status</th></tr></thead><tbody>${S.pay.slice(-4).reverse().map(p=>`<tr><td data-label="Member"><span class="table-person"><span class="avatar">${initials(p.m)}</span><b>${p.m}</b></span></td><td data-label="Amount">${fmt(p.amt)}</td><td data-label="Reference">${p.ref}</td><td data-label="Date">${p.date}</td><td data-label="Status">${badge(p.st)}</td></tr>`).join('')}</tbody></table></div></section>
 <div class="dashboard-links"><a href="members.html"><i class="fa-solid fa-users"></i><span><b>Manage members</b><small>View your group roster</small></span><i class="fa-solid fa-arrow-right"></i></a><a href="transactions.html"><i class="fa-solid fa-arrow-right-arrow-left"></i><span><b>Record a payout</b><small>Update your group ledger</small></span><i class="fa-solid fa-arrow-right"></i></a><button id="reset-demo" class="text-button">Reset demo data</button></div>`;
 const collection=[['Apr',200000],['May',200000],['Jun',180000],['Jul',200000],['Aug',200000],['Sep',confirmed()]],peak=Math.max(...collection.map(x=>x[1]),1);
 $('#collection-chart').innerHTML=collection.map(([month,value])=>`<div class="chart-column"><span class="chart-value">₦${Math.round(value/1000)}k</span><div class="chart-track"><span style="height:${Math.max(value/peak*100,2)}%"></span></div><small>${month}</small></div>`).join('');
 $('#reset-demo').onclick=()=>confirmAction('Reset all demo data?',()=>{localStorage.removeItem(K);S=seed();S.user={role:'admin',name:'Adebayo Ogunleye',username:'adebayo',email:''};save();location.reload()});
}

function renderAdminContributions(){
 const pending=S.pay.filter(p=>p.st==='wait').length;
 main.innerHTML=`${pageHead('CONTRIBUTIONS',team.cycle,'Review member payments and keep this cycle up to date.')}
 <section class="stat-grid">${statCard('Expected',fmt(team.amt*S.pay.length),'fa-bullseye')}${statCard('Confirmed',fmt(confirmed()),'fa-circle-check')}${statCard('Pending review',pending,'fa-hourglass-half')}${statCard('Rejected',S.pay.filter(p=>p.st==='bad').length,'fa-circle-exclamation')}</section>
 <section class="panel"><div class="panel-heading"><div><span class="eyebrow">PAYMENT REGISTER</span><h2>Member contributions</h2></div><span class="badge b-info">${team.cycle}</span></div><div class="table-wrap"><table><thead><tr><th>Member</th><th>Amount</th><th>Reference</th><th>Date</th><th>Status</th><th>Actions</th></tr></thead><tbody id="contribution-rows">${contributionRows()}</tbody></table></div></section>`;
 main.onclick=e=>{const confirmButton=e.target.closest('[data-confirm-payment]'),rejectButton=e.target.closest('[data-reject-payment]');if(confirmButton){const payment=S.pay.find(p=>p.id==confirmButton.dataset.confirmPayment);if(payment){payment.st='ok';save();renderAdminContributions();toast('Payment confirmed. Balance updated.')}}if(rejectButton){const payment=S.pay.find(p=>p.id==rejectButton.dataset.rejectPayment);if(payment)confirmAction('Reject this payment? The member will be asked to resubmit.',()=>{payment.st='bad';save();renderAdminContributions();toast('Payment rejected',1)})}};
}

function renderAdminMembers(){
 main.innerHTML=`${pageHead('YOUR GROUP','Members',`Manage the ${NAMES.length} members in ${team.name}.`,'<a class="btn" href="invite.html"><i class="fa-solid fa-user-plus"></i> Invite member</a>')}<section class="panel"><div class="panel-heading"><div><span class="eyebrow">GROUP ROSTER</span><h2>All members</h2></div><input id="member-search" class="search-input" type="search" placeholder="Search members" aria-label="Search members"></div><div class="table-wrap"><table><thead><tr><th>Member</th><th>Username</th><th>Monthly</th><th>This cycle</th><th>Total contributed</th></tr></thead><tbody id="member-rows">${memberRows()}</tbody></table></div></section>`;
 $('#member-search').oninput=e=>{$('#member-rows').innerHTML=memberRows(e.target.value)};
}

function renderAdminTransactions(){
 main.innerHTML=`${pageHead('LEDGER','Transactions','Review payouts already sent by your group. AJO does not move money.')}
 <section class="panel payout-panel"><div><span class="eyebrow">NEXT RECIPIENT · ${team.cycle}</span><h2>John Doe</h2><p>Expected payout <b>${fmt(team.amt*S.pay.length)}</b></p></div><button class="btn" id="record-payout"><i class="fa-solid fa-plus"></i> Record payout</button></section>
 <section class="panel"><div class="panel-heading"><div><span class="eyebrow">PAYOUT HISTORY</span><h2>Recorded transactions</h2></div><span class="badge b-info">${S.disb.length} payout${S.disb.length===1?'':'s'}</span></div><div class="table-wrap"><table><thead><tr><th>Month</th><th>Recipient</th><th>Amount</th><th>Reference</th><th>Status</th></tr></thead><tbody>${S.disb.map(d=>`<tr><td data-label="Month">${d.mon}</td><td data-label="Recipient">${d.to}</td><td data-label="Amount">${fmt(d.amt)}</td><td data-label="Reference">${d.ref}</td><td data-label="Status"><span class="badge b-ok">Recorded</span></td></tr>`).join('')}</tbody></table></div></section>
 <section class="panel"><div class="panel-heading"><div><span class="eyebrow">PAYOUT ORDER</span><h2>Group schedule</h2></div></div><ol class="schedule-list">${S.order.map(o=>`<li class="${o[2]}"><span class="schedule-dot"></span><span><b>${o[0]}</b><small>${o[1]}</small></span>${o[2]==='done'?'<span class="badge b-ok">Paid out</span>':o[2]==='now'?'<span class="badge b-info">Current</span>':''}</li>`).join('')}</ol></section>
 <div class="modal" id="payout-modal" role="dialog" aria-modal="true" aria-labelledby="payout-title"><div class="modal-card"><button class="modal-close" data-close-modal aria-label="Close"><i class="fa-solid fa-xmark"></i></button><h2 id="payout-title">Record a payout</h2><p class="muted">Record a payout you already sent. AJO does not move money.</p><form id="payout-form" novalidate><label for="d1">Recipient</label><input id="d1" readonly><label for="d2">Amount (₦)</label><input id="d2" type="number" min="1"><label for="d3">Bank name</label><input id="d3" placeholder="Access Bank"><label for="d4">Account name</label><input id="d4"><label for="d5">Account number</label><input id="d5" inputmode="numeric" maxlength="10"><label for="d6">Transaction reference</label><input id="d6"><label for="d7">Date</label><input id="d7" type="date"><label for="d8">Note (optional)</label><input id="d8"><div class="modal-actions"><button type="button" class="btn secondary" data-close-modal>Cancel</button><button class="btn">Confirm payout</button></div></form></div></div>`;
 $('#record-payout').disabled=S.disb.some(d=>d.cur);
 $('#record-payout').textContent=S.disb.some(d=>d.cur)?'Payout recorded':'Record payout';
 $('#record-payout').onclick=()=>{if(S.disb.some(d=>d.cur))return;$('#d1').value='John Doe';$('#d2').value=team.amt*S.pay.length;$('#d7').valueAsDate=new Date();modal('payout-modal')};
 main.querySelectorAll('[data-close-modal]').forEach(button=>button.onclick=()=>modal('payout-modal',false));
 $('#payout-form').onsubmit=e=>{e.preventDefault();const amount=+$('#d2').value,get=id=>$('#d'+id).value.trim();if(!amount||!get(3)||!get(4)||get(5).length!==10||!get(6))return toast('Complete bank name, account name, 10-digit account number and reference',1);if(amount>balance())return toast(`Amount is more than the recorded Ajo Balance (${fmt(balance())})`,1);S.disb.unshift({to:'John Doe',mon:team.cycle,amt:amount,ref:get(6),cur:true});S.order[1][2]='done';S.order[2][2]='now';save();modal('payout-modal',false);renderAdminTransactions();toast('Payout recorded. Balance updated.')};
}

function renderInvite(){
 const link='https://ajo.app/join/'+team.code;
 main.innerHTML=`${pageHead('GROW YOUR GROUP','Invite members',`Share a secure invitation to ${team.name}.`)}<section class="panel invite-panel"><span class="invite-icon"><i class="fa-solid fa-link"></i></span><h2>Your team invite</h2><p>Anyone joining with this link becomes a <b>member</b> of this team, never an admin.</p><label for="invite-link">Invitation link</label><div class="linkbox"><input id="invite-link" readonly value="${link}"><button class="btn" id="copy-invite"><i class="fa-regular fa-copy"></i> Copy link</button><a class="btn secondary" id="share-invite" target="_blank" rel="noopener"><i class="fa-brands fa-whatsapp"></i> WhatsApp</a></div><p class="muted">${NAMES.length} invited · ${NAMES.length} joined · 0 pending</p></section>`;
 $('#share-invite').href='https://wa.me/?text='+encodeURIComponent(`Join our Ajo team "${team.name}" on AJO: ${link}`);
 $('#copy-invite').onclick=()=>navigator.clipboard.writeText(link).then(()=>toast('Invitation link copied'),()=>toast('Copy failed. Select the link and copy it manually.',1));
}

function renderMemberDashboard(){
 const payment=S.pay.find(p=>p.m===S.user.name),paid=S.pay.filter(p=>p.st==='ok').length;
 const recent=S.pay.filter(p=>p.m===S.user.name).slice(-3).reverse();
 main.innerHTML=`${pageHead('MEMBER SPACE',`Welcome, ${(S.user.name||'Member').split(' ')[0]}`,team.name)}
 <section class="stat-grid">${statCard('Monthly contribution',fmt(team.amt),'fa-coins')}${statCard('This cycle',payment?payment.st==='ok'?'Paid':payment.st==='wait'?'Awaiting review':'Resubmit':'Not paid','fa-circle-check')}${statCard('Ajo balance',fmt(balance()),'fa-wallet')}${statCard('Current recipient','John Doe','fa-hand-holding-dollar')}</section>
 <section class="dashboard-columns"><article class="panel"><div class="panel-heading"><div><span class="eyebrow">${team.cycle.toUpperCase()}</span><h2>Contribution progress</h2></div><span class="badge b-info">${paid} / ${S.pay.length}</span></div><div class="progress-copy"><b>Members paid</b><span>${Math.round(paid/Math.max(S.pay.length,1)*100)}%</span></div><div class="progress-track"><span style="width:${paid/Math.max(S.pay.length,1)*100}%"></span></div><a class="text-link" href="contributions.html">View contribution details <i class="fa-solid fa-arrow-right"></i></a></article><article class="panel next-payout"><span class="eyebrow">UP NEXT</span><h2>John Doe</h2><p>September recipient</p><span class="payout-amount">${fmt(team.amt*S.pay.length)}</span></article></section>
 <section class="panel"><div class="panel-heading"><div><span class="eyebrow">RECENT ACTIVITY</span><h2>My contributions</h2></div><a class="text-link" href="transactions.html">View transactions</a></div>${recent.length?`<ul class="activity-list">${latestActivity(recent.map(p=>({title:team.cycle,note:`Reference ${p.ref}`,value:fmt(p.amt),icon:'fa-arrow-up-right-from-square',tone:p.st==='ok'?'positive':''})))}</ul>`:'<p class="empty-state">Your submitted contributions will appear here.</p>'}<a class="btn" href="contributions.html">${payment&&payment.st==='ok'?'View contribution':'Make a contribution'}</a></section>`;
}

function renderMemberContributions(){
 const payment=S.pay.find(p=>p.m===S.user.name),canPay=!payment||payment.st==='bad',bank=team.bank;
 main.innerHTML=`${pageHead('CONTRIBUTIONS',team.cycle,'Make your monthly contribution and check its confirmation status.')}
 <section class="stat-grid">${statCard('Monthly amount',fmt(team.amt),'fa-coins')}${statCard('Payment status',payment?payment.st==='ok'?'Confirmed':payment.st==='wait'?'Pending review':'Resubmit':'Not submitted','fa-circle-check')}${statCard('Current recipient','John Doe','fa-user-check')}</section>
 <section class="contribution-layout"><article class="panel"><div class="panel-heading"><div><span class="eyebrow">TRANSFER DETAILS</span><h2>Pay your contribution</h2></div></div><div class="bank-details"><div><small>Bank</small><b>${bank.bank}</b></div><div><small>Account name</small><b>${bank.name}</b></div><div><small>Account number</small><b>${bank.no}</b></div></div>${payment&&payment.st==='ok'?'<p class="status-message success"><i class="fa-solid fa-circle-check"></i> Your payment is confirmed for this cycle.</p>':payment&&payment.st==='wait'?'<p class="status-message warning"><i class="fa-solid fa-clock"></i> Your payment has been submitted and is awaiting admin confirmation.</p>':payment?'<p class="status-message danger">Your last payment was rejected. Update the details and resubmit.</p>':''}${canPay?`<form id="member-payment" novalidate><label for="amount">Amount (₦)</label><input id="amount" type="number" min="1" value="${team.amt}"><label for="payment-date">Payment date</label><input id="payment-date" type="date"><label for="reference">Transaction reference</label><input id="reference" placeholder="e.g. TRX88421"><label for="receipt">Receipt (optional)</label><input id="receipt" type="file" accept="image/*,.pdf"><button class="btn block" type="submit">Submit for confirmation</button></form>`:''}</article>
 <article class="panel"><span class="eyebrow">HOW IT WORKS</span><h2>Payment confirmation</h2><p class="muted">Transfer your contribution directly to the group account, then submit the transaction reference. Your admin will verify it and update the shared ledger.</p><div class="progress-copy"><b>Group payment progress</b><span>${S.pay.filter(p=>p.st==='ok').length}/${S.pay.length}</span></div><div class="progress-track"><span style="width:${S.pay.filter(p=>p.st==='ok').length/Math.max(S.pay.length,1)*100}%"></span></div><a class="text-link" href="transactions.html">See my transaction history <i class="fa-solid fa-arrow-right"></i></a></article></section>`;
 if(canPay){$('#payment-date').valueAsDate=new Date();$('#member-payment').onsubmit=e=>{e.preventDefault();if(!+$('#amount').value||!$('#reference').value.trim()||!$('#payment-date').value)return toast('Enter amount, date and transaction reference',1);S.pay=S.pay.filter(x=>x.m!==S.user.name);S.pay.push({id:Date.now(),m:S.user.name,amt:+$('#amount').value,ref:$('#reference').value.trim(),date:$('#payment-date').value,st:'wait'});save();renderMemberContributions();toast('Payment submitted. Awaiting admin confirmation.')}}
}

function renderMemberTransactions(){
 const payment=S.pay.find(p=>p.m===S.user.name),history=[['September 2026',payment?payment.st:'wait'],...['August','July','June','May','April'].map(month=>[`${month} 2026`,'ok'])];
 main.innerHTML=`${pageHead('ACTIVITY','Transactions','A record of your submitted contributions and their status.')}<section class="panel"><div class="panel-heading"><div><span class="eyebrow">CONTRIBUTION HISTORY</span><h2>My transactions</h2></div></div><div class="table-wrap"><table><thead><tr><th>Cycle</th><th>Amount</th><th>Status</th></tr></thead><tbody>${history.map(([month,status])=>`<tr><td data-label="Cycle">${month}</td><td data-label="Amount">${fmt(team.amt)}</td><td data-label="Status">${badge(status)}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">PAYOUT ORDER</span><h2>Group schedule</h2></div></div><ol class="schedule-list">${S.order.map(o=>`<li class="${o[2]}"><span class="schedule-dot"></span><span><b>${o[0]}</b><small>${o[1]}</small></span>${o[2]==='now'?'<span class="badge b-info">Current</span>':o[2]==='done'?'<span class="badge b-ok">Paid out</span>':''}</li>`).join('')}</ol></section>`;
}

function renderProfile(){
 main.innerHTML=`${pageHead('ACCOUNT','Profile','Your AJO account and group information.')}<section class="profile-grid"><article class="panel profile-card"><span class="profile-avatar">${initials(S.user.name||'AJO')}</span><span class="eyebrow">${role==='admin'?'GROUP ADMIN':'GROUP MEMBER'}</span><h2>${S.user.name}</h2><p class="muted">${S.user.email||'No email on file'}</p><dl class="profile-details"><div><dt>Username</dt><dd>@${S.user.username||S.user.name.split(' ')[0].toLowerCase()}</dd></div><div><dt>Role</dt><dd>${role==='admin'?'Admin':'Member'}</dd></div></dl><button class="btn secondary" id="profile-logout"><i class="fa-solid fa-right-from-bracket"></i> Log out</button></article><article class="panel"><span class="eyebrow">YOUR GROUP</span><h2>${team.name}</h2><dl class="profile-details"><div><dt>Contribution cycle</dt><dd>${team.cycle}</dd></div><div><dt>Monthly contribution</dt><dd>${fmt(team.amt)}</dd></div><div><dt>Invite code</dt><dd>${team.code}</dd></div></dl>${role==='admin'?'<a class="btn" href="invite.html">Invite members</a>':''}</article></section>`;
 $('#profile-logout').onclick=logout;
}

function confirmAction(message,onConfirm){
 let dialog=$('#action-confirm');
 if(!dialog){dialog=document.createElement('div');dialog.id='action-confirm';dialog.className='modal';dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.innerHTML='<div class="modal-card"><h2>Confirm action</h2><p id="confirm-message"></p><div class="modal-actions"><button class="btn secondary" data-cancel>Cancel</button><button class="btn danger-button" data-confirm>Confirm</button></div></div>';document.body.append(dialog);dialog.querySelector('[data-cancel]').onclick=()=>modal('action-confirm',false)}
 $('#confirm-message').textContent=message;dialog.querySelector('[data-confirm]').onclick=()=>{modal('action-confirm',false);onConfirm()};modal('action-confirm');
}

const renderers={admin:{dashboard:renderAdminDashboard,contributions:renderAdminContributions,members:renderAdminMembers,transactions:renderAdminTransactions,invite:renderInvite,profile:renderProfile},member:{dashboard:renderMemberDashboard,contributions:renderMemberContributions,transactions:renderMemberTransactions,profile:renderProfile}};
const render=renderers[role][route];
if(render)render();else location.replace('dashboard.html');
}